apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80  # The port exposed on the service
      targetPort: 5000  # The port on which your application runs inside the pods
